#gh
name: PyGoat CI - SAST

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  sonar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Download Sonar Scanner
        run: |
          curl -sSLo sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
          unzip sonar-scanner.zip

      - name: Verify Sonar secrets exist
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      run: |
        if [ -z "$SONAR_TOKEN" ]; then echo "SONAR_TOKEN IS EMPTY"; exit 1; else echo "SONAR_TOKEN OK"; fi
        if [ -z "$SONAR_HOST_URL" ]; then echo "SONAR_HOST_URL IS EMPTY"; exit 1; else echo "SONAR_HOST_URL OK"; fi

      - name: Run SonarQube Scan
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      run: |
        ./sonar-scanner-*/bin/sonar-scanner \
           -Dsonar.projetKey=pygoat \
           -Dsonar.sources=,\
           -Dsonar.host.url=$SONAR_HOST_URL \
           -Dsonar.token=$SONAR_TOKEN

      - name: SonarQube Quality Gate
      uses: sonarsource/sonarqube-quality-gate-action@v1
      timeout-minutes: 5
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: Verify token exists
        run: |
          if [ -z "$SONAR_TOKEN" ]; then echo "TOKEN IS EMPTY"; exit 1; else echo "TOKEN IS PRESENT"; fi
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Run SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          export SONAR_TOKEN=$SONAR_TOKEN
          ./sonar-scanner-*/bin/sonar-scanner

